#!/usr/bin/python3
# -*- coding: utf-8 -*-

import os
from ec_local_param import *

__author__ = 'Pavan Mahalingam'


class EcAppParam:
    """
    Static class containing all the global parameters which do not depend on the environment (dev/qualif/prod).
    """

    # transfer of local params from LocalParam to EcAppParam
    gcm_prodEnv = LocalParam.gcm_prodEnv
    gcm_appDomain = LocalParam.gcm_appDomain
    gcm_httpPort = LocalParam.gcm_httpPort
    gcm_dbServer = LocalParam.gcm_dbServer
    gcm_dbUserLocal = LocalParam.gcm_dbUserLocal
    gcm_dbPasswordLocal = LocalParam.gcm_dbPasswordLocal
    gcm_debugModeOn = LocalParam.gcm_debugModeOn
    gcm_verboseModeOn = LocalParam.gcm_verboseModeOn
    gcm_mailSender = LocalParam.gcm_mailSender
    gcm_smtpServer = LocalParam.gcm_smtpServer
    gcm_amazonSmtp = LocalParam.gcm_amazonSmtp
    gcm_sesIamUser = LocalParam.gcm_sesIamUser
    gcm_sesUserName = LocalParam.gcm_sesUserName
    gcm_sesPassword = LocalParam.gcm_sesPassword
    gcm_appRoot = LocalParam.gcm_appRoot
    gcm_gmailSmtp = LocalParam.gcm_gmailSmtp
    gcm_mailSenderPassword = LocalParam.gcm_mailSenderPassword
    gcm_browser = LocalParam.gcm_browser
    gcm_headless = LocalParam.gcm_headless
    gcm_expansionCount = LocalParam.gcm_expansionCount
    gcm_max_story_count = LocalParam.gcm_max_story_count
    gcm_getImages = LocalParam.gcm_getImages
    gcm_startGathering = LocalParam.gcm_startGathering
    gcm_debugToDB = LocalParam.gcm_debugToDB

    #: Static files root (copied from :any:`LocalParam`)
    gcm_staticRoot = LocalParam.gcm_appRoot

    # general parameters
    #: Application name (used in many contexts like logger names, cookie name, etc)
    gcm_appName = 'RBSFB'
    #: Application version (dev version with three figures)
    gcm_appVersion = '0.0.0'
    #: App description (used in title of HTML pages ...)
    gcm_appTitle = 'FB scraping Web Service for ROAD B SCORE'

    # HTTP server parameters

    #: Cookie lifetime in days (100 years)
    gcm_cookiePersistence = 365*100

    #: Cookie name for the terminal ID
    gcm_sessionName = 'ECTerminalID_{0}'.format(gcm_appName)

    # Database parameters
    #: Database name
    gcm_dbDatabase = 'RBSFB'
    #: Database username (copied from :any:`LocalParam`)
    gcm_dbUser = gcm_dbUserLocal
    #: Database password (copied from :any:`LocalParam`)
    gcm_dbPassword = gcm_dbPasswordLocal

    #: Min size of DB connection pool
    gcm_connectionPoolMinCount = 10
    #: Max size of DB connection pool
    gcm_connectionPoolMaxCount = 5

    #: Flag to disable the connection pool feature. If `True` then new connection creation on each request.
    #: Not active at the moment.
    gcm_noConnectionPool = False

    #: average browser driver life span (in hours) and diameter
    gcm_bdLifeAverage = .5
    gcm_bdLifeDiameter = .25

    # Logging
    #: Recipients of e-mail messages generated by the logging system
    gcm_mailRecipients = ['nicolas.reimen@gmail.com', 'nrtmp@free.fr']
    #: Location of CSV log file
    gcm_logFile = os.path.join(gcm_appRoot, 'Log/ec_log.csv')

    # headless browser screen size
    gcm_headlessWidth = 1200
    gcm_headlessHeight = 2000

    # non-headless browser size
    gcm_width = 1200
    gcm_height = 1000

    gcm_minImageSize = 100

    gcm_sessionDisplayCount = 100


